StoreUI/Models/HistoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StoreUI.Models
{
    public class HistoryViewModel
    {
        public int Id { get; set; }
        public string State { get; set; }
    }
}

StoreUI/Models/LaptopViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StoreUI.Models
{
    public class LaptopViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Processor { get; set; }
        [Required]
        public string RAM { get; set; }
        [Required]
        public string VideoCard { get; set; }
        [Required]
        public string Disc { get; set; }
        [Required]
        public double? Price { get; set; }
        [Required]
        public string Description { get; set; }
     
        public string LaptopType { get; set; }
      
        public string Developer { get; set; }
     
        public string Image { get; set; }
        public int LaptopTypeId { get; set; }
        public int DeveloperId { get; set; }
    }
}

StoreUI/Models/OrderDetailsViewModel.cs
using BLL.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StoreUI.Models
{
    public class OrderDetailsViewModel
    {
        public int Id { get; set; }
        public string LaptopName {get;set;}
        public string LaptopImage { get; set; }
        public int LaptopPrice { get; set; }
        public int LaptopId { get; set; }
    }
}

StoreUI/Controllers/LaptopsController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Filters;
using BLL.Interfaces;
using StoreUI.Models;
using StoreUI.Utils.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using StoreUI.Utils;
using BLL.Managers;

using Microsoft.AspNet.Identity.EntityFramework;

namespace StoreUI.Controllers
{
    public class LaptopsController : Controller
    {

        private readonly ILaptopService _laptopService;
        private readonly IMapper _mapper;
        private string userId { get { return User.Identity.GetUserId(); } }
        private ApplicationUserManager manager { get { return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); } }


        public LaptopsController(ILaptopService laptopService, IMapper mapper)
        {
            _laptopService = laptopService;
            _mapper = mapper;

        }
        public async Task<ActionResult> Index(string search)
        {
            setViewBag();
            ViewBag.Title = "LaptopStore";


            var currentUser = await manager.FindByIdAsync(userId);
            if (currentUser != null)
            {
                if (currentUser.Carts.Count == 0)
                {
                    await CreateCart();
                }
                if (currentUser.Carts.Count != 0)
                    ViewBag.BinCount = currentUser.Carts.LastOrDefault().cartItems.Count();
                ViewBag.OrdersCount = _laptopService.GetOrderCart().Where(x=>x.State=="In Process").ToList().Count;

            }
            var laptops = _laptopService.GetAllLaptops(null);
            if (String.IsNullOrEmpty(search))
            {
                ViewBag.Laptops = laptops;
                return View();
            }
            ViewBag.Laptops = laptops.Where(x => x.Name.Contains(search)).ToList();
            return View();

        }
        private void setViewBag()
        {
            ViewBag.Types = _laptopService.GetTypes();
            ViewBag.Developers = _laptopService.GetDevelopers();
            ViewBag.BinCount = 0;
        }
        public ActionResult Create()
        {
            SelectList types = new SelectList(_laptopService.GetAllTypes(), "Id", "Name");
            ViewBag.Types = types;
            SelectList devs = new SelectList(_laptopService.GetAllDevelopers(), "Id", "Name");
            ViewBag.Developers = devs;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(LaptopViewModel model, HttpPostedFileBase image)
        {
            if (!ModelState.IsValid)
            {
                return View("Error");
            }
            if (image != null)
            {

                var fileName = Guid.NewGuid() + ".jpg";
                var bitmap = BitmapConvertor.Convert(image.InputStream, 200, 200);
                var serverPath = Server.MapPath($"~/Images/{fileName}");
                bitmap.Save(serverPath);
                model.Image = $"/Images/{fileName}";
            }

            await _laptopService.AddLaptopAsync(_mapper.Map<LaptopDTO>(model));
            return RedirectToAction("Index");
        }

        public ActionResult Filter(string type, string value)
        {
            var filter = new LaptopsFilter()
            {
                Name = value,
                Type = type
            };

            if (type == "developer")
            {
                filter.Predicate = (x => x.Developer.Name == value);
            }
            else if (type == "type")
            {
                filter.Predicate = (x => x.LaptopType.Name == value);
            }
            else if (type == "ram")
            {
                filter.Predicate = (x => x.RAM == value);

            }
            var filters = new List<LaptopsFilter>();
            if (Session["LaptopsFilter"] != null)
            {
                filters = Session["LaptopsFilter"] as List<LaptopsFilter>;
            }
            var found = filters.FirstOrDefault(f => f.Name == value && f.Type == type);

            if (found != null)
            {
                filters.Remove(found);
            }
            else
            {
                filters.Add(filter);
            }
            Session["LaptopsFilter"] = filters;


            var laptops = _laptopService.GetAllLaptops(filters);
            ViewBag.Laptops = laptops;

            return PartialView("LaptopsPartial", ViewBag);

        }
        private LaptopViewModel GetViewModel(int id)
        {
            LaptopDTO laptop = _laptopService.GetAllLaptops(null).Where(x => x.Id == id).FirstOrDefault();
            LaptopViewModel l = new LaptopViewModel()
            {
                Name = laptop.Name,
                Processor = laptop.Processor,
                RAM = laptop.RAM,
                VideoCard = laptop.VideoCard,
                Disc = laptop.Disc,
                Price = laptop.Price,
                Description = laptop.Description,
                Image = laptop.Image,
                Developer = _laptopService.GetAllDevelopers().Where(x => x.Id == laptop.DeveloperId).FirstOrDefault().Name,
                LaptopType = _laptopService.GetAllTypes().Where(x => x.Id == laptop.LaptopTypeId).FirstOrDefault().Name
            };
            return l;

        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            return View(GetViewModel((int)id));
        }
        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            await _laptopService.DeleteAsync((int)id);
            return RedirectToAction("Index");
        }
        [HttpGet]

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            SelectList types = new SelectList(_laptopService.GetAllTypes(), "Id", "Name", id);
            ViewBag.Types = types;
            SelectList devs = new SelectList(_laptopService.GetAllDevelopers(), "Id", "Name", id);
            ViewBag.Developers = devs;

            return View(GetViewModel((int)id));
        }

        [HttpPost]

        public async Task<ActionResult> Edit(LaptopViewModel model, HttpPostedFileBase image)
        {
            if (image != null)
            {
                var fileName = Guid.NewGuid() + ".jpg";
                var bitmap = BitmapConvertor.Convert(image.InputStream, 200, 200);
                var serverPath = Server.MapPath($"~/Images/{fileName}");
                bitmap.Save(serverPath);
                model.Image = $"/Images/{fileName}";
            }
            await _laptopService.EditAsync(_mapper.Map<LaptopDTO>(model));
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            return View(GetViewModel(id));

        }
        public async Task<ActionResult> AddToCart(int id)
        {
            var user = await manager.FindByIdAsync(userId);
            CartItemDTO order = new CartItemDTO()
            {
                LaptopId = id,
                CartId = (user.Carts.LastOrDefault()).Id
            };

            await _laptopService.AddOrder(order);
            return RedirectToAction("Index");

        }

        private async Task CreateCart()
        {
            var user = await manager.FindByIdAsync(userId);

            if (user.Carts.Count == 0)
            {
                CartDTO cart = new CartDTO()
                {

                    UserId = userId,
                    MakeOrder = false,
                    State = "In Process"
                };
                await _laptopService.AddCart(cart);
            }

        }
        public async Task<ActionResult> Cart()
        {
            await SetCartViewBag();
            return View();
        }

        private async Task SetCartViewBag()
        {
            var currentUser = await manager.FindByIdAsync(userId);
            ViewBag.Items = currentUser.Carts.LastOrDefault().cartItems;
            ViewBag.BinCount = currentUser.Carts.LastOrDefault().cartItems.Count();
            ViewBag.Price = Price();
        }
        public async Task<ActionResult> DeleteOrder(int id)
        {

            await _laptopService.DeleteOrder(id);
            await SetCartViewBag();

            return RedirectToAction("Cart");
        }

        private double Price()
        {
            var currentUser = manager.FindById(userId);

            double? price = 0;

            for (int i = 0; i < currentUser.Carts.LastOrDefault().cartItems.Count(); i++)
            {
                price += (currentUser.Carts.LastOrDefault().cartItems).ToArray()[i].Laptop.Price;
            }
            return (double)price;
        }
        public async Task<ActionResult> MakeOrder()
        {
            var currentUser = await manager.FindByIdAsync(userId);

            var Cart = currentUser.Carts.LastOrDefault();
            if (Cart.cartItems.Count != 0)
            {

                var CartId = Cart.Id;
                CartDTO cart = new CartDTO()
                {
                    Id = CartId,
                    UserId = currentUser.Id,
                    State = "In Process",
                    MakeOrder = true
                };

                await _laptopService.EditCart(cart);

                CartDTO cart2 = new CartDTO()
                {
                    UserId = currentUser.Id,
                    MakeOrder = false,
                    State = "In Process"
                };
                await _laptopService.AddCart(cart2);
            }
            else
            {

StoreUI/Views/Laptops/Cart.cshtml
@using System.Web.Optimization
@model IEnumerable<DAL.Entities.CartItem>

@{
    ViewBag.Title = "Cart";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
@Styles.Render("~/Content/css")
<div class="container mt-4">
    <h1>Ваша Корзина</h1>
    <div class="row">

    <div class="col-9">
        <style>
            th, tr, td {
                border: 1px solid black
            }
        </style>

        <table class="table">
            <tr>
                <th>
                    <h3>@Html.DisplayNameFor(model => model.Laptop.Image)</h3>
                </th>

                <th>
                    <h3>@Html.DisplayNameFor(model => model.Laptop.Name)</h3>
                </th>
              
                <th>
                    <h3>@Html.DisplayNameFor(model => model.Laptop.Price)</h3>

                </th>
                <th>
                    <h3>Options</h3>

                </th>
            </tr>

            @foreach (var item in ViewBag.Items)
            {
                <tr>
                    <td>
                        <img src="@item.Laptop.Image" width="150" />
                    </td>
                    <td>
                        <h3 class="text-danger">@item.Laptop.Name</h3>
                    </td>
                  
                    <td>
                        <h2 class="text-warning">@item.Laptop.Price $</h2>

                    </td>
                    <td>
                            <input class="btn btn-sm btn-danger" type="submit" onclick="DeleteOrder(@item.Id)" value="Удалить" />
                    </td>
                </tr>
            }
        <tr>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </tr>

        </table>
    </div>
    <div class="col-3">
        <h3 class="text-danger">Your order:</h3>
        <p>Total amount of items: <span class="text-danger">@ViewBag.Items.Count</span></p>
        <p>Total price: <span class="text-danger"><span>@ViewBag.Price</span> $</span></p>
        @if(ViewBag.Items.Count!=0)
        {
        @Html.ActionLink("Make Order", "MakeOrder", "", new { @class = "btn btn-primary" })
        }
     
    </div>

    </div>
</div>

StoreUI/Views/Laptops/Create.cshtml
@model StoreUI.Models.LaptopViewModel

@{
    ViewBag.Title = "TOPSTORE";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}


@using (Html.BeginForm("Create", "Laptops", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal container mt-4">
        <h2>Create</h2>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Processor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Processor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Processor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RAM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RAM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RAM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoCard, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoCard, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoCard, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Disc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Disc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Disc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-2">
                <input type="radio" onclick="ChoosenUrlImg()" id="radioUrlImg" name="img" />
                <label for="radioUrlImg">Image Url</label>
            </div>
            <div class="col-md-2">
                <input type="radio" onclick="ChoosenLocalImg()" id="radioFileImg" name="img" />
                <label class="" for="radioFileImg">Local Image</label>
            </div>

            <div class="col-md-2">
                <input type="file" name="image" id="localImg" placeholder="choose" />
                <input type="text" name="image" id="urlimage" placeholder="enter URL" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LaptopTypeId, ViewBag.Types as SelectList, "Select Types", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LaptopTypeId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DeveloperId, ViewBag.Developers as SelectList, "Choose Developer", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DeveloperId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

StoreUI/Views/Laptops/Delete.cshtml
@model StoreUI.Models.LaptopViewModel

@{
    ViewBag.Title = "TOPSTORE";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<div class="container mt-5">

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Processor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Processor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RAM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RAM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VideoCard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoCard)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Disc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Disc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LaptopType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaptopType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Developer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Developer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dt>
            <img src="@Model.Image" width="200" />
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index","", new { @class = "btn btn-primary" })
        </div>
    }
</div>
</div>

StoreUI/Views/Laptops/Details.cshtml
@model  StoreUI.Models.LaptopViewModel
@{
    ViewBag.Title = "Details";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />

</head>
<body>
    <div class="container-fluid ">
        <div class="container ">
            <div class="row block1 mt-3 pb-3">
                <div class="col-12">
                    <div class="col-12 text-center " id="img">
                        <h1>@Model.Name</h1>
                        <img src=@Model.Image class="img2" width="500" alt="Alternate Text" />
                    </div>
                    <div class="col-12">
                        <div class="row">
                            <div class="col-2 text-center">
                                <h2 class="m-0">
                                    Processor:
                                </h2>
                                <h3 class="m-0">
                                    @Model.Processor

                                </h3>
                            </div>

                            <div class="col-2 text-center">
                                <h2 class="m-0">
                                    RAM
                                </h2>
                                <h3 class="m-0">
                                    @Model.RAM

                                </h3>
                            </div>

                            <div class="col-2 text-center">
                                <h2 class="m-0">
                                    VideoCard:
                                </h2>
                                <h3 class="m-0">
                                    @Model.VideoCard

                                </h3>
                            </div>

                            <div class="col-2 text-center">
                                <h2 class="m-0">
                                    Disc
                                </h2>
                                <h3 class="m-0">
                                    @Model.Disc

                                </h3>
                            </div>

                            <div class="col-2 text-center">
                                <h2 class="m-0">
                                    Developer
                                </h2>
                                <h3 class="m-0">
                                    @Model.Developer

                                </h3>
                            </div>
                            <div class="col-2 text-center">
                                <h2 class="m-0">
                                    Type
                                </h2>
                                <h3 class="m-0">
                                    @Model.LaptopType

                                </h3>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row text-center mt-3 pb-3">
                <div class="col-12">
                    <h2>Description:</h2>
                    <h4>@Model.Description</h4>
                </div>
                <div class="col-12">
                    <div class="row d-flex justify-content-center">
                        @Html.ActionLink("Back To List", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>

            </div>

        </div>
    </div>
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/popper.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/custom.js"></script>
</body>

</html>

StoreUI/Views/Laptops/Edit.cshtml
@model StoreUI.Models.LaptopViewModel

@{

    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}


@using (Html.BeginForm("Edit", "Laptops", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal container">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Processor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Processor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Processor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RAM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RAM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RAM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoCard, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoCard, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoCard, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Disc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Disc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Disc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LaptopType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LaptopTypeId, ViewBag.Types as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LaptopTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Developer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DeveloperId, ViewBag.Developers as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DeveloperId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Model.Image" width="600" />
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="custom-control-label col-md-2">
                New Image
            </div>
            <div class="col-md-2">
                <input type="radio" onclick="ChoosenUrlImg()" id="radioUrlImg" name="img" />
                <label for="radioUrlImg">Image Url</label>
            </div>
            <div class="col-md-2">
                <input type="radio" onclick="ChoosenLocalImg()" id="radioFileImg" name="img" />
                <label class="" for="radioFileImg">Local Image</label>
            </div>
            <div class="col-md-2">
                <input type="file" name="image" id="localImg" placeholder="choose" />
                <input type="text" name="image" id="urlimage" placeholder="enter URL" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                @Html.ActionLink("Back to List", "Index","", new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}